In [9]:
import numpy                                     #  numpy 불러오기

In [10]:
array1 = numpy.array([2,3, 5, 7, 11, 13, 17, 19])   # numpy array 함수 사용 

In [11]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [12]:
type(array1)   #ndarray 는 n차원배열을 의미함 

numpy.ndarray

In [13]:
array1.shape    # array1에 몇개의 요소가 있는지 확인하기 

(8,)

In [14]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [15]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
type(array2)

numpy.ndarray

In [17]:
array2.shape  

(3, 4)

In [18]:
array1.size

8

In [19]:
array2.size   #3x4 

12

In [21]:
# 실습

In [22]:
import numpy 


array1 = numpy.full(6,0)
array2 = numpy.random.random(6)

In [24]:
import numpy as np                                       # as np붙여주기


array1 = np.full(6,0)
array2 = np.random.random(6)

In [25]:
array1

array([0, 0, 0, 0, 0, 0])

In [26]:
array2

array([0.68976741, 0.0437732 , 0.3290556 , 0.06373652, 0.26588462,
       0.97122344])