In [1]:
import numpy as np

In [2]:
array1 = np.array ([2,3,5,7,11,13,15,17,19,23])  # 인덱스 넣어주기 인덱스는 0 부터 숫자를 읽음

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23])

In [5]:
array1[0]     #0번째 인덱스 값 불러오기 (인덱싱)

2

In [6]:
array1[5]

13

In [7]:
array1[-1]

23

In [8]:
array1[[1,3,4]]   # python 리스트로 인덱스 값 불러오기 

array([ 3,  7, 11])

In [9]:
array2 = np.array([2, 1, 3])

In [11]:
array1[array2]   # numpy array로 인덱스 값 불러오기 

array([5, 3, 7])

In [12]:
array1 [2:7]   # 슬라이싱 2번 인덱스부터 7번 인덱스까지 불러오기 

array([ 5,  7, 11, 13, 15])

In [15]:
array1

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23])

In [17]:
array1[2:6:3]  #2번부터 6번 인덱스까지 숫자 3개 건너뛰기 

array([ 5, 13])