▲리스트2.31 : NumPy의 임포트

In [1]:
import numpy

▲리스트2.32 : 모듈에 다른 이름을 붙인다

In [2]:
import numpy as np

▲리스트2.33 : Python의 리스트로부터 NumPy의 배열을 만든다 

In [3]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])  # Python의 리스트로부터 NumPy 배열을 만든다
print(a) 

[0 1 2 3 4 5]


▲리스트2.34 : 2중 리스트로부터 NumPy의 2차원 배열을 만든다

In [4]:
import numpy as np

b = np.array([[0, 1, 2], [3, 4, 5]])  # 2중 리스트로부터 NumPy의 2차원 배열을 만든다
print(b)

[[0 1 2]
 [3 4 5]]


▲리스트2.35 : 3중 리스트로부터 NumPy의 3차원 배열을 만든다

In [5]:
import numpy as np

c = np.array([[[0, 1, 2], [3, 4, 5]], [[5, 4, 3], [2, 1, 0]]])  # 3중 리스트로부터 NumPy의 3차원 배열을 만든다
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


▲리스트2.36 : 배열을 생성하는 여러 가지 함수

In [6]:
import numpy as np

d = np.zeros(8)  # 0이 8개 저장된 배열
print(d)

e = np.ones(8) # 1이 8개 저장된 배열
print(e)

f = np.arange(8) # 0부터 7까지가 저장된 배열
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


▲리스트2.37 : shape( ) 함수에 의해 배열의 형태를 얻는다

In [7]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2x3의 2차원배열
print(np.shape(a))  # a의 형태를 표시

(2, 3)


▲리스트2.38 : 'len( )'에 의해 가장 바깥쪽의 요소수를 얻는다

In [8]:
print(len(a))  # a의 행 수를 얻는다

2


▲리스트2.39 : 배열과 수치의 연산

In [9]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2차원 배열

print(a) 
print()
print(a + 3)  # 각 요소에 3을 더한다
print()
print(a * 3)  # 각 요소에 3을 곱한다

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


▲리스트2.40 : 배열끼리의 연산

In [10]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2차원 배열

c = np.array([[2, 0, 1],
              [5, 3, 4]])  # 2차원 배열

print(b)
print()
print(c)
print()
print(b + c)
print()
print(b * c)

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


▲리스트2.41 : 인덱스를 지정하고, 배열의 요소에 접근한다

In [11]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[3])  # 인덱스를 지정

4


▲리스트2.42 : 인덱스를 지정하여, 배열의 요소를 바꿔 넣는다

In [12]:
a[2] = 9
print(a)

[1 2 9 4 5]


▲리스트2.43 : 2차원 배열의 요소에 접근한다

In [13]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])

print(b[1, 2])  # b[1][2]와 같다

5


▲리스트2.44 : 2차원 배열의 요소를 바꿔 넣는다

In [14]:
b[1, 2] = 9

print(b)

[[0 1 2]
 [3 4 9]]


▲리스트2.45 : 행이나 열에 접근한다

In [15]:
c = np.array([[0, 1, 2],
              [3, 4, 5]])

print(c[1, :])  # 인덱스가 1인 행을 취득 

print()

c[:, 1] = np.array([6, 7])  # 인덱스가 1인 열을 교체
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


In [17]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2차원배열

print("합계:", np.sum(a))
print("평균:", np.average(a))
print("최댓값:", np.max(a))
print("최솟값:", np.min(a))

합계: 15
평균: 2.5
최댓값: 5
최솟값: 0


#### □문제

　Jupyter Notebook의 셀에 NumPy의 2차원 배열을 두 개 기술하고, 두 개의 합, 차, 곱을 구합시다(리스트2.48).

#### □정답 예

▲리스트2.48: 정답 예

In [18]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])
b = np.array([[5, 4, 3],
              [2, 1, 0]])

print(a + b)  # 합
print()
print(a - b)  # 차
print()
print(a * b)  # 곱

[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]

[[0 4 6]
 [6 4 0]]
